![CC-BY-SA](https://mirrors.creativecommons.org/presskit/buttons/88x31/svg/by-sa.svg)
This notebook was created by [Bernardo Freitas Paulo da Costa](http://www.im.ufrj.br/bernardofpc),
and is licensed under Creative Commons BY-SA

# Implementando `numpy.linalg.solve()`

Vamos implementar a nossa própria versão de "solve".
A principal razão para fazê-lo é que a versão do `numpy` não é "genérica", ou seja,
ela não funciona para uma matriz qualquer, mas apenas para matrizes de números.
E poderíamos ter um sistema linear cujos coeficientes não fossem números.

Por exemplo, imagine que queremos resolver o seguinte sistema:
$$\begin{align*}
e^t x + e^{-t}y + \ e^{3t} z & = 2 \\
e^t x - e^{-t}y + 3e^{3t} z& = -1 \\
e^t x + e^{-t}y + 9e^{3t} z& = 1
\end{align*}$$
As variáveis $x$ e $y$ são **funções** de $t$,
mas o mais importante é que este é um _sistema linear_ em $t$,
logo podemos aplicar a mesma ideia da eliminação de Gauss!

## Eliminação

Para resolver um sistema linear, procedemos em duas etapas.
A primeira é conhecida como "eliminação de Gauss", que vai eliminando sucessivamente os coeficientes.

In [17]:
import numpy as np

In [18]:
def elim(A,b, debug=False):
    """Elimina as equações do sistema Ax = b, de cima para baixo.
    Os dados de entrada são _alterados_ pela execução da função, para refletir o novo sistema."""
    A = np.array(A)
    b = np.array(b)
    m,n = np.shape(A)
    ### Resposta aqui
    if m < n:
        menor = m
    else:
        menor = n
    for i in range(menor):      # i Representa linhas
        linha_i = A[i]
        pivot = A[i][i]
        
        if debug:
            print(i)
            print('')
            print(A)
            print('')
            print(b)
            print('-=' * 50)
        
        for ii in range(i+1, m):  # ii Representa linhas
            nova_linha = A[ii] - (linha_i / pivot) * A[ii][i]
            novo_b = b[ii] - (b[i] / pivot) * A[ii][i]
            
            A[ii] = nova_linha
            b[ii] = novo_b
            
    if debug:
            print('end')
            print(A)
            print(b)
    
    return A, b

In [19]:
A = [[1,2,3],[4,5,6],[7,8,9]]
A, np.shape(A)

([[1, 2, 3], [4, 5, 6], [7, 8, 9]], (3, 3))

In [20]:
b = [1,3,3]

In [21]:
elim(A,b, debug=True)

0

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 3 3]
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1

[[  1   2   3]
 [  0  -3  -6]
 [  0  -6 -12]]

[ 1 -1 -4]
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
2

[[ 1  2  3]
 [ 0 -3 -6]
 [ 0  0  0]]

[ 1 -1 -2]
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
end
[[ 1  2  3]
 [ 0 -3 -6]
 [ 0  0  0]]
[ 1 -1 -2]


(array([[ 1,  2,  3],
        [ 0, -3, -6],
        [ 0,  0,  0]]),
 array([ 1, -1, -2]))

In [22]:
A, b

([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1, 3, 3])

In [23]:
A = np.random.rand(4,4)
b = np.random.rand(4)
elim(A,b)

(array([[ 0.58069226,  0.0921862 ,  0.48330252,  0.2673167 ],
        [ 0.        , -0.0591432 ,  0.45691793,  0.38978425],
        [ 0.        ,  0.        ,  0.43042235,  0.20404421],
        [ 0.        ,  0.        ,  0.        ,  0.7566553 ]]),
 array([ 0.46429261,  0.57101525,  0.81336474, -1.61798786]))

In [24]:
A = np.random.rand(3,4)
b = np.random.rand(3)
elim(A,b)

(array([[0.25372653, 0.63147022, 0.16196534, 0.5640237 ],
        [0.        , 0.08156509, 0.69509056, 0.34606619],
        [0.        , 0.        , 6.38730758, 2.02739384]]),
 array([0.48455533, 0.36586049, 2.61548381]))

In [25]:
A = np.random.rand(4,3)
b = np.random.rand(4)
elim(A,b)

(array([[ 0.64034934,  0.04896001,  0.97523265],
        [ 0.        ,  0.85523479, -0.24963037],
        [ 0.        ,  0.        , -0.46936672],
        [ 0.        ,  0.        ,  0.        ]]),
 array([ 0.29897766, -0.18337138,  0.32241299,  0.09012435]))

## Substituição

A segunda etapa consiste em resolver "de fato" o sistema, de baixo para cima.
Como encontramos as soluções e vamos substituindo os valores nas respectivas equações,
este etapa se chama substituição.

In [26]:
def subst(A,b):
    """Substitui as equações do sistema Ax = b, de baixo para cima,
    e retorna o vetor x das soluções, sem alterar A nem b."""
    m,n = np.shape(A)
    # Verifique que a matriz A está correta
    ### Resposta aqui
    A = np.array(A)
    b = np.array(b)
    
    for i in range(m-1, -1, -1):
        pivot = A[i][i]
        
        for ii in range(i-1, -1, -1):
            novo_b = b[ii] - (b[i]/pivot)*A[ii][i]
            
            A[ii][i] = 0
            b[ii] = novo_b
        
        b[i] = b[i] / pivot
        A[i][i] = 1
        
    return b

In [27]:
A = [
    [4,0,0],
    [0,5,0],
    [0,0,6]
]
b = [4, 10, 18]

A,b = elim(A,b)
print(subst(A, b))

[1 2 3]


### Exercício

Um dos maiores problemas do nosso código de eliminação é que ele modifica a matriz.
Isso é ruim para verificar se a solução encontrada pela substituição satisfaz a equação original.
(Podemos verificar que satisfaz o sistema "eliminado", pois a substituição não modifica $A$ ou $b$).

Corrija isso, e verifique que o procedimento duplo (eliminação + substituição)
de fato encontra uma solução.

In [28]:
A = np.random.rand(4,4)
b = np.random.rand(4)
U, b_ = elim(A,b)
x = subst(U,b_)
# deveria dar bem perto de zero!
np.dot(A,x) - b

array([ 0.00000000e+00,  1.11022302e-16, -2.22044605e-16,  1.11022302e-16])

In [29]:
def solve(A,b):
    U,b_ = elim(A,b)
    return subst(U,b_)

In [30]:
x1 = solve(A,b)
x2 = np.linalg.solve(A,b)
x1 - x2

array([ 4.71844785e-16,  2.22044605e-16, -3.60822483e-16,  0.00000000e+00])

In [31]:
np.dot(A,x1) - b, np.dot(A,x2) - b

(array([ 0.00000000e+00,  1.11022302e-16, -2.22044605e-16,  1.11022302e-16]),
 array([0., 0., 0., 0.]))

# Aplicação: sistemas racionais

In [32]:
from fractions import Fraction

In [33]:
A = [[3,2,3],[4,7,6],[7,8,7]]
b = [1,2,1]

In [34]:
AF = [[Fraction(aij) for aij in ai] for ai in A]
bF = [Fraction(bi) for bi in b]

In [35]:
elim(AF, bF, debug=True)

0

[[Fraction(3, 1) Fraction(2, 1) Fraction(3, 1)]
 [Fraction(4, 1) Fraction(7, 1) Fraction(6, 1)]
 [Fraction(7, 1) Fraction(8, 1) Fraction(7, 1)]]

[Fraction(1, 1) Fraction(2, 1) Fraction(1, 1)]
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1

[[Fraction(3, 1) Fraction(2, 1) Fraction(3, 1)]
 [Fraction(0, 1) Fraction(13, 3) Fraction(2, 1)]
 [Fraction(0, 1) Fraction(10, 3) Fraction(0, 1)]]

[Fraction(1, 1) Fraction(2, 3) Fraction(-4, 3)]
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
2

[[Fraction(3, 1) Fraction(2, 1) Fraction(3, 1)]
 [Fraction(0, 1) Fraction(13, 3) Fraction(2, 1)]
 [Fraction(0, 1) Fraction(0, 1) Fraction(-20, 13)]]

[Fraction(1, 1) Fraction(2, 3) Fraction(-24, 13)]
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
end
[[Fraction(3, 1) Fraction(2, 1) Fraction(3, 1)]
 [Fraction(0, 1) Fraction(13, 3) Fraction(2, 1)

(array([[Fraction(3, 1), Fraction(2, 1), Fraction(3, 1)],
        [Fraction(0, 1), Fraction(13, 3), Fraction(2, 1)],
        [Fraction(0, 1), Fraction(0, 1), Fraction(-20, 13)]], dtype=object),
 array([Fraction(1, 1), Fraction(2, 3), Fraction(-24, 13)], dtype=object))

In [36]:
elim(AF, bF, debug=True)

0

[[Fraction(3, 1) Fraction(2, 1) Fraction(3, 1)]
 [Fraction(4, 1) Fraction(7, 1) Fraction(6, 1)]
 [Fraction(7, 1) Fraction(8, 1) Fraction(7, 1)]]

[Fraction(1, 1) Fraction(2, 1) Fraction(1, 1)]
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1

[[Fraction(3, 1) Fraction(2, 1) Fraction(3, 1)]
 [Fraction(0, 1) Fraction(13, 3) Fraction(2, 1)]
 [Fraction(0, 1) Fraction(10, 3) Fraction(0, 1)]]

[Fraction(1, 1) Fraction(2, 3) Fraction(-4, 3)]
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
2

[[Fraction(3, 1) Fraction(2, 1) Fraction(3, 1)]
 [Fraction(0, 1) Fraction(13, 3) Fraction(2, 1)]
 [Fraction(0, 1) Fraction(0, 1) Fraction(-20, 13)]]

[Fraction(1, 1) Fraction(2, 3) Fraction(-24, 13)]
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
end
[[Fraction(3, 1) Fraction(2, 1) Fraction(3, 1)]
 [Fraction(0, 1) Fraction(13, 3) Fraction(2, 1)

(array([[Fraction(3, 1), Fraction(2, 1), Fraction(3, 1)],
        [Fraction(0, 1), Fraction(13, 3), Fraction(2, 1)],
        [Fraction(0, 1), Fraction(0, 1), Fraction(-20, 13)]], dtype=object),
 array([Fraction(1, 1), Fraction(2, 3), Fraction(-24, 13)], dtype=object))

In [37]:
solve(AF, bF)

array([Fraction(-3, 5), Fraction(-2, 5), Fraction(6, 5)], dtype=object)

In [38]:
np.linalg.solve(A,b)

array([-0.6, -0.4,  1.2])

In [39]:
np.linalg.solve(AF,bF)

UFuncTypeError: Cannot cast ufunc 'solve1' input 0 from dtype('O') to dtype('float64') with casting rule 'same_kind'