![CC-BY-SA](https://mirrors.creativecommons.org/presskit/buttons/88x31/svg/by-sa.svg)


This notebook was created by [Bernardo Freitas Paulo da Costa](http://www.im.ufrj.br/bernardofpc),
and is licensed under Creative Commons BY-SA.

Antes de enviar este Teste, verifique que tudo está funcionando como esperado.
Por exemplo, **rode o código inteiro, do zero**.
Para isso, vá no menu, escolha _Kernel_, depois _Restart & Run All_.

Verifique, também, que você respondeu todas as questões:
* as questões de código têm `YOUR CODE HERE` (e você pode apagar o `raise NotImplemented` ao incluir sua resposta)
* as questões discursivas têm "YOUR ANSWER HERE".

---

In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Convergência de vetores na iteração QR

Vamos ver como os vetores das matrizes $Q$ do algoritmo QR iterativo convergem para os autovetores de $A = QDQ^T$.

## Gerando matrizes diagonalizáveis aleatórias

Para inclusive poder verificar sem problemas a qualidade da diagonalização,
vamos gerar matrizes ortogonais aleatórias $Q$ e matrizes diagonais aleatórias $D$.

Uma forma muito simples de gerar matrizes ortogonais aleatórias é fazer a fatoração QR de uma matriz $A$ qualquer
(veja a função `np.linalg.qr`).

### Questão 1. Parte ortogonal

Escreva uma função que, dado $n$, retorne uma matriz aleatória $n \times n$ ortogonal.

In [7]:
def randq(n):
    # YOUR CODE HERE
    A = np.random.rand(n, n)   # Cria uma matriz aleatória
    Q = np.linalg.qr(A)[0]  # Pega a parte ortogonal da decomposição QR
    
    return Q

Verificando que ela é ortogonal:

In [8]:
i = np.identity(20)
for _ in range(10):
    Q = randq(20)
    assert np.allclose(Q.T @ Q, i)

Verificando que é aleatória

In [9]:
np.random.seed(1)
for _ in range(10):
    n = np.random.randint(30,100)
    prev = randq(n)
    for _ in range(3):
        nova = randq(n)
        assert np.linalg.norm(prev - nova)**2 >= n/2

### Questão 2. Matriz diagonalizável

Agora, escreva uma função que, dado $n$, retorna uma matriz diagonalizável aleatória $n \times n$,
cujos autovalores sejam reais aleatórios entre $-n$ e $n$.
Retorne também os autovalores num vetor `a_val`
e os autovetores correspondentes numa lista (de arrays `numpy`) `a_vet`.

In [53]:
import random


def rand_diag(n):
    """Creio que seja interessante definirmos aleatoriamente os autovalores e os autovetores, e assim sim achar a matriz usando a decomposição espectral."""
    
    a_val = [random.uniform(-n, n) for _ in range(n)]
    D = np.diag(a_val)

    P = randq(n)

    A = (P@D)@P.T
    
    print(A)
    return A, a_val, P

Verificando que realmente vale $Av = \lambda v$:

In [54]:
for _ in range(3):
    A,ls,vs = rand_diag(3)
    for l,v in zip(ls,vs):
        print(A@v - l*v)

[[ 1.46491714 -0.34558122 -0.7534855 ]
 [-0.34558122  1.17974     1.68054717]
 [-0.7534855   1.68054717 -2.23100668]]
[-0.60789365  0.54766204  1.18138188]
[1.03728973 0.41720764 0.90460974]
[-1.13407142  0.08536901  0.19068601]
[[-0.57560693 -1.27331157  0.37433593]
 [-1.27331157 -0.29618624  0.43508345]
 [ 0.37433593  0.43508345 -0.87559797]]
[ 0.58378861 -0.01413642 -0.23575921]
[ 0.66968447 -0.3663272   0.484527  ]
[ 0.7127781   0.6391635  -0.21746141]
[[-0.99532737  0.07779804 -1.02709811]
 [ 0.07779804 -1.97951586 -0.58449522]
 [-1.02709811 -0.58449522  0.92733023]]
[ 0.29851413  0.33243384 -1.54609707]
[-0.24212676  0.15102835  0.73928862]
[-0.32706832 -1.73708711 -0.44954247]


In [55]:
for _ in range(20):
    A,ls,vs = rand_diag(30)
    for l,v in zip(ls,vs):
        assert np.allclose(A@v, l*v)

[[ 2.07949332e+00  1.13762453e+00 -3.73484211e-01  1.20924806e+00
   3.57614188e+00 -3.64117714e+00  4.88349123e+00 -5.87319971e+00
   4.20389548e+00  1.12222962e+00  8.30233152e+00 -7.57971740e-01
   2.45387881e+00 -1.90261211e+00  2.40010901e+00 -3.47045563e+00
  -4.96632997e-01 -3.19702634e-01  3.61916499e-01  3.00471509e-01
   3.78325925e+00 -1.56346438e+00  2.85567888e+00  5.52871578e+00
   1.30626475e+00 -3.56380877e+00 -4.52240070e-01  2.04884920e+00
   1.32080632e-01 -4.50192703e+00]
 [ 1.13762453e+00  1.48317114e+00  6.25036987e+00  1.17625934e+00
   3.60281199e+00 -6.78627272e-01  1.80151415e+00 -6.40140166e-01
   5.80950737e-01 -2.45607069e+00  1.27980956e+00 -3.54582487e+00
   2.15075156e-01 -1.54063023e+00 -9.01805273e-01 -1.30069856e+00
   2.82654822e+00  1.19061675e+00  2.55430238e+00 -2.25984950e+00
  -2.54811207e+00 -3.41714818e+00  1.37657434e+00 -6.56370479e-01
   6.26811404e+00  1.85028907e+00 -1.19387170e+00 -4.80527686e-01
   1.72343230e-01 -1.16036189e+00]
 [-3.7

AssertionError: 

In [ ]:
np.random.seed(2)
for _ in range(20):
    A,ls,vs = rand_diag(35)
    # Há (bastantes) autovalores positivos e negativos
    assert sum(ls < 0) > 5
    assert sum(ls > 0) > 5

### Questão 3. Autovetores ordenados

Modifique rand_diag para que os autovalores venham em ordem decrescente do módulo.
A função `argsort` pode ser útil: não queremos mudar o sinal dos autovalores, mas precisamos ordenar `abs(a_val)`.

In [ ]:
def rand_diag(n):
    # YOUR CODE HERE
    raise NotImplementedError()

In [ ]:
np.random.seed(2)
for _ in range(20):
    A,ls,vs = rand_diag(30)
    for l1,l2 in zip(ls[:-1], ls[1:]):
        assert abs(l1) > abs(l2)
    for l,v in zip(ls,vs):
        assert np.allclose(A@v, l*v)
    # Há (bastantes) autovalores positivos e negativos
    assert sum(ls < 0) > 5
    assert sum(ls > 0) > 5

## CVGA Projetivo

Vamos usar o ângulo entre vetores para obter uma velocidade de convergência.
Lembre que $\cos \theta = \frac{u\cdot v}{|u| \cdot |v|}$.

Se temos uma base ortogonal $e_i$, e uma base $u_i = \pm e_i$,
elas estão "alinhadas", por mais que os vetores possam estar com o sentido trocado.
Por isso, não vamos usar o ângulo ("orientado") dado pela fórmula acima,
mas o **menor** ângulo $\hat\theta$ entre as retas determinadas por $u$ e $v$.
Este é bastante parecido:
$$ \cos \hat\theta = \frac{|u\cdot v|}{|u| \cdot |v|}. $$

Este ângulo é importante em geometria projetiva, porque apenas a direção das retas importa, não a sua orientação.

### Questão 4. Função ângulo

Usando a fórmula anterior, escreva uma função que calcula o ângulo entre as retas de direção $u$ e $v$.

In [ ]:
def proj_angle(u,v):
    # YOUR CODE HERE
    raise NotImplementedError()

In [ ]:
assert(proj_angle([1,0], [0,1]) == np.pi/2)
assert(proj_angle([1,0], [1,0]) == 0)

## Algoritmo QR: iteração de bases

O algoritmo QR iterado, dada uma matriz $A$,
repetidamente usa a fatoração QR para diagonalizá-la.
Começando com uma matriz $Q_0$ qualquer (em geral, a identidade), em cada etapa, o algoritmo

1. Fatora a matriz $A Q_{n-1}$ como $Q_n R_n$
2. Se $R_n$ for "quase diagonal" (use a função `np.allclose`), retorna
3. Senão, itera

Estas operações correspondem a aplicar a ideia da iteração direta não apenas em um vetor, mas em uma _base_.

### Questão 5. QR com bases

Escreva a função `itera_qr` que retorna as matrizes $Q_n$ e $R_n$ em listas.
A matriz $Q_n$ pode ser vista como tendo em suas colunas uma "base" de vetores
que está "convergindo" para a base de autovetores de $A$.

In [ ]:
def itera_qr(A, maxiter=1000):
    Q0 = np.identity(A.shape[0])
    Qs = []
    Rs = []
    # YOUR CODE HERE
    raise NotImplementedError()

#### 5.1 Qn ortogonais

Este é fácil.

In [ ]:
np.random.seed(3)
for n in np.random.randint(4,8, size=10):
    A, _, _ = rand_diag(n)
    i = np.identity(n)
    Qs,_ = itera_qr(A)
    for Qn in Qs:
        assert np.allclose(i, Qn @ Qn.T)

#### 5.2 $R_n$ quase diagonal.

No fim do algoritmo, teremos em $R_n$ a candidata para a matriz dos autovalores de $A$.

(Observação: dependendo da versão do numpy que você usar, pode ser que a diagonal de $R$ tenha apenas valores positivos.  Neste caso, insira um comentário abaixo, e troque o segundo `assert` para `abs(a_vals)`, para verificar no seu computador se o seu algoritmo está funcionando.)

In [ ]:
np.random.seed(32)
for n in np.random.randint(4,8, size=10):
    A, a_vals, _ = rand_diag(n)
    _,Rs = itera_qr(A, maxiter=5000)
    d_Rs = Rs[-1].diagonal()
    assert np.allclose(Rs[-1], np.diag(d_Rs))
    assert np.allclose(d_Rs, a_vals)

### 6. Distância entre bases

Escreva uma função que, dadas duas matrizes $B_1$ e $B_2$ (representando bases do $R^n$),
calcula as distâncias entre os vetores **linhas** correspondentes, e as retona num array ou lista.
(usaremos vetores linhas, e não colunas, porque são estes que vêm na lista `a_vec`;
atenção, a matriz $Q$ tem a base nas colunas...)

In [ ]:
def base_distances(B1,B2):
    # YOUR CODE HERE
    raise NotImplementedError()

In [ ]:
I3 = np.identity(3)
assert all(base_distances(I3, I3) == np.array([0,0,0]))
assert all(base_distances(I3, -I3) == np.array([2,2,2]))

In [ ]:
I3 = np.identity(3)
assert all(base_distances(I3, [[0,1,0], [0,0,1],[1,0,0]]) == np.sqrt(np.array([2,2,2])))
assert all(base_distances(I3, [[1,0,0], [0,1,0], [1,0,1]]) == np.array([0,0,1]))

### 7. Autovetores

Com ajuda função anterior, faça um gráfico da evolução da distância (euclidiana)
entre os autovetores de uma matriz $3\times 3$ (aleatória, diagonalizável)
e os vetores correspondentes vindos da iteração QR.

In [ ]:
np.random.seed(5)
A, _, a_vec = rand_diag(3)
Qs,_ = itera_qr(A)
# YOUR CODE HERE
raise NotImplementedError()

### 8. Ângulos

Agora, em vez de calcular a distância entre os vetores,
faça o gráfico do ângulo entre as retas respectivas,
como já fizemos no início.

Aproveite a ideia da função que calcula a distância entre bases para fazer uma `base_angles` análoga.

In [ ]:
def base_angles(B1,B2):
    # YOUR CODE HERE
    raise NotImplementedError()

In [ ]:
np.random.seed(6)
A, _, a_vec = rand_diag(4)
Qs,Rs = itera_qr(A)
# YOUR CODE HERE
raise NotImplementedError()
plt.legend(['$v_{}$'.format(i) for i in range(4)], loc=0);

### 9. Velocidade de convergência

Use os ângulos calculados para estimar a taxa de convergência de cada vetor para o autovetor correspondente.
Como isso se relaciona com os autovalores calculados?

In [ ]:
### Contas aqui
# YOUR CODE HERE
raise NotImplementedError()

YOUR ANSWER HERE

### 10. Precisão para o ângulo projetivo

Se você fez corretamente o gráfico anterior,
algumas linhas pararam de aparecer por volta de $10^{-8} = \sqrt{\epsilon}$.
Isso se deve à imprecisão do computador ao calcular $\arccos(1 - x)$ com $x$ muito pequeno.
Para contornar isso, vamos usar uma fórmula estável para o ângulo.

Se temos dois vetores $u$ e $v$, podemos projetar (como fizemos) $v$ em $u$ e obter o cosseno do ângulo entre eles.
Para contornar o problema de precisão quando $u$ e $v$ estão quase alinhados,
vamos dar mais informação ao nosso programa: vamos calcular o **seno** do ângulo também.
Para isso, "Gram-Schmidt": basta retirar de $v$ a componente na direção de $u$.
O que restar será ortogonal a $u$, e será proporcional ao seno do ângulo entre $v$ e $u$.
Faça um desenho para ver!

Com todos os detalhes: dados $u$ e $v$,
determine a projeção de $v$ em $u$ (com um produto interno) e o vetor restante por subtração.
Agora, use a função `arctan2` que recebe dois comprimentos $y$ e $x$ (nesta ordem "errada")
e dá o ângulo do ponto $(x,y)$ com relação ao eixo X.
Como esta função usa ambas as coordenadas, ela não sofre os mesmos problemas de precisão que `arccos`.

In [ ]:
def proj_angle_prec(u,v):
    # YOUR CODE HERE
    raise NotImplementedError()

Testando ângulos "normais"

In [ ]:
np.random.seed(98765)
for n in np.random.randint(4,10,size=10):
    u = np.random.rand(n)
    v = np.random.rand(n)
    assert proj_angle(u,v) - proj_angle_prec(u,v) < 1e-15

Testando ângulos "pequenos"

In [ ]:
assert proj_angle_prec([1,0,0,0], [1,0,1e-15,1e-15]) == np.sqrt(2)*1e-15 - 2e-31

### 11. Convergência das bases

Faça agora o gráfico do ângulo entre as bases da iteração QR,
e veja-os diminuirem até $10^{-16}$ como esperado.

In [ ]:
np.random.seed(999)
A, _, a_vec = rand_diag(5)
Qs,_ = itera_qr(A)
# YOUR CODE HERE
raise NotImplementedError()